# 1. Nombre de la App
spring.application.name=PriceStocker

# 2. Conexión a Base de Datos (Traducido de tu config.properties)
spring.datasource.url=jdbc:postgresql://localhost:5432/PriceStocker
spring.datasource.username=postgres
spring.datasource.password=Valm_2109072_
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configuración de JPA / Hibernate
# "update" creará las tablas si no existen, o las actualizará si cambias el modelo.
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola (útil para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. Evitar errores con JavaFX
spring.main.web-application-type=none