-- ==========================================
-- 1. TABLAS INDEPENDIENTES (CATÁLOGOS)
-- ==========================================

CREATE TABLE usuario (
    idusuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreusuario VARCHAR(50) NOT NULL UNIQUE,
    contrasenausuario VARCHAR(255) NOT NULL,
    permiso BOOLEAN DEFAULT FALSE
);

CREATE TABLE categoria (
    idcategoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombrecategoria VARCHAR(100) NOT NULL UNIQUE,
    desccategoria TEXT,
    descripcion_categoria VARCHAR(255)
);

-- ==========================================
-- 2. TABLAS PRINCIPALES (ENTIDADES)
-- ==========================================

CREATE TABLE cliente (
    idcliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombrecliente VARCHAR(100) NOT NULL,
    cpcliente INT NOT NULL,
    noextcliente INT NOT NULL,
    nointcliente VARCHAR(20),
    rfccliente VARCHAR(13),
    municipio VARCHAR(100) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    calle VARCHAR(100) NOT NULL,
    colonia VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    pais VARCHAR(50) NOT NULL,
    telefonocliente VARCHAR(15) NOT NULL,
    correocliente VARCHAR(100) NOT NULL,
    curpcliente VARCHAR(18),
    pfisicacliente BOOLEAN DEFAULT TRUE
);

CREATE TABLE proveedor (
    idproveedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreprov VARCHAR(100) NOT NULL,
    cpproveedor INT NOT NULL,
    noextprov INT NOT NULL,
    nointprov VARCHAR(20),
    rfcproveedor VARCHAR(13),
    municipio VARCHAR(100) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    calle VARCHAR(100) NOT NULL,
    colonia VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    pais VARCHAR(50) NOT NULL,
    telefonoprov VARCHAR(15) NOT NULL,
    correoprov VARCHAR(100) NOT NULL,
    curpproveedor VARCHAR(18),
    pfisicaproveedor BOOLEAN DEFAULT TRUE,
    curp VARCHAR(255)
);

CREATE TABLE empresa (
    idempresa INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreemp VARCHAR(100) NOT NULL,
    cpempresa INT NOT NULL,
    noextempresa INT NOT NULL,
    nointempresa VARCHAR(20),
    rfcempresa VARCHAR(13),
    municipio VARCHAR(100) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    calle VARCHAR(100) NOT NULL,
    colonia VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    pais VARCHAR(50) NOT NULL,
    telefonoempresa VARCHAR(15) NOT NULL,
    correoempresa VARCHAR(100) NOT NULL,
    curpempresa VARCHAR(18),
    pfisicaempresa BOOLEAN DEFAULT TRUE
);

CREATE TABLE fabricante (
    idfabricante INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombrefabricante VARCHAR(100) NOT NULL,
    cpfabricante INT NOT NULL,
    noextfabricante INT NOT NULL,
    nointfabricante VARCHAR(20),
    rfcfabricante VARCHAR(13),
    municipio VARCHAR(100) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    calle VARCHAR(100) NOT NULL,
    colonia VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    pais VARCHAR(50) NOT NULL,
    telefonofabricante VARCHAR(15) NOT NULL,
    correofabricante VARCHAR(100) NOT NULL,
    curpfabricante VARCHAR(18),
    pfisicafabricante BOOLEAN DEFAULT TRUE
);

CREATE TABLE prestadorservicio (
    idprestador INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreprestador VARCHAR(100) NOT NULL,
    cpprestador INT NOT NULL,
    noextprestador INT NOT NULL,
    nointprestador VARCHAR(20),
    rfcprestador VARCHAR(13),
    municipio VARCHAR(100) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    calle VARCHAR(100) NOT NULL,
    colonia VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    pais VARCHAR(50) NOT NULL,
    telefonoprest VARCHAR(15) NOT NULL,
    correoprest VARCHAR(100) NOT NULL,
    curpprestador VARCHAR(18),
    pfisicaprestador BOOLEAN DEFAULT TRUE
);

-- ==========================================
-- 3. PRODUCTOS Y SERVICIOS
-- ==========================================

CREATE TABLE producto (
    idproducto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreproducto VARCHAR(100) NOT NULL,
    fichaproducto TEXT,
    alternoproducto VARCHAR(100),
    existenciaproducto INT DEFAULT 0,
    precioproducto DOUBLE PRECISION DEFAULT 0.0
);

CREATE TABLE servicio (
    idservicio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idprestador INT,
    descripcionservicio TEXT NOT NULL,
    costoservicio DOUBLE PRECISION NOT NULL,
    monedaservicio VARCHAR(3) NOT NULL CHECK (monedaservicio IN ('MXN', 'USD')),
    FOREIGN KEY (idprestador) REFERENCES prestadorservicio(idprestador)
);

-- ==========================================
-- 4. TABLAS DE RELACIÓN (PRODUCTO - PRECIOS)
-- ==========================================

CREATE TABLE productocliente (
    idproducto INT NOT NULL,
    idcliente INT NOT NULL,
    costoventa DOUBLE PRECISION NOT NULL,
    monedaventa VARCHAR(3) NOT NULL CHECK (monedaventa IN ('MXN', 'USD')),
    PRIMARY KEY (idproducto, idcliente),
    FOREIGN KEY (idproducto) REFERENCES producto(idproducto),
    FOREIGN KEY (idcliente) REFERENCES cliente(idcliente)
);

CREATE TABLE productoproveedor (
    idproducto INT NOT NULL,
    idproveedor INT NOT NULL,
    costocompraprov DOUBLE PRECISION NOT NULL,
    monedacompraprov VARCHAR(3) NOT NULL CHECK (monedacompraprov IN ('MXN', 'USD')),
    PRIMARY KEY (idproducto, idproveedor),
    FOREIGN KEY (idproducto) REFERENCES producto(idproducto),
    FOREIGN KEY (idproveedor) REFERENCES proveedor(idproveedor)
);

CREATE TABLE productoempresa (
    idproducto INT NOT NULL,
    idempresa INT NOT NULL,
    costomercado DOUBLE PRECISION NOT NULL,
    monedamercado VARCHAR(3) NOT NULL CHECK (monedamercado IN ('MXN', 'USD')),
    PRIMARY KEY (idproducto, idempresa),
    FOREIGN KEY (idproducto) REFERENCES producto(idproducto),
    FOREIGN KEY (idempresa) REFERENCES empresa(idempresa)
);

CREATE TABLE productofabricante (
    idproducto INT NOT NULL,
    idfabricante INT NOT NULL,
    costocomprafab DOUBLE PRECISION NOT NULL,
    monedacomprafab VARCHAR(3) NOT NULL CHECK (monedacomprafab IN ('MXN', 'USD')),
    PRIMARY KEY (idproducto, idfabricante),
    FOREIGN KEY (idproducto) REFERENCES producto(idproducto),
    FOREIGN KEY (idfabricante) REFERENCES fabricante(idfabricante)
);

CREATE TABLE productoservicio (
    idproducto INT NOT NULL,
    idservicio INT NOT NULL,
    PRIMARY KEY (idproducto, idservicio),
    FOREIGN KEY (idproducto) REFERENCES producto(idproducto),
    FOREIGN KEY (idservicio) REFERENCES servicio(idservicio)
);

-- ==========================================
-- 5. TABLAS DE CATEGORÍAS (RELACIONES)
-- ==========================================

CREATE TABLE productocategoria (
    idproducto INT NOT NULL,
    idcategoria INT NOT NULL,
    PRIMARY KEY (idproducto, idcategoria),
    FOREIGN KEY (idproducto) REFERENCES producto(idproducto),
    FOREIGN KEY (idcategoria) REFERENCES categoria(idcategoria)
);

-- ==========================================
-- 6. TABLAS DE COMPRAS Y VENTAS
-- ==========================================

CREATE TABLE venta (
    idventa INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_venta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    idcliente INT,
    idusuario INT NOT NULL,
    total_venta DOUBLE PRECISION NOT NULL DEFAULT 0,
    FOREIGN KEY (idcliente) REFERENCES cliente(idcliente),
    FOREIGN KEY (idusuario) REFERENCES usuario(idusuario)
);

CREATE TABLE detalle_venta (
    iddetalleventa INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idventa INT NOT NULL,
    idproducto INT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario DOUBLE PRECISION NOT NULL,
    subtotal DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (idventa) REFERENCES venta(idventa) ON DELETE CASCADE,
    FOREIGN KEY (idproducto) REFERENCES producto(idproducto)
);

CREATE TABLE compra (
    idcompra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_compra TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    idproveedor INT,
    idfabricante INT,
    idusuario INT NOT NULL,
    total_compra DOUBLE PRECISION NOT NULL DEFAULT 0,
    FOREIGN KEY (idproveedor) REFERENCES proveedor(idproveedor),
    FOREIGN KEY (idfabricante) REFERENCES fabricante(idfabricante),
    FOREIGN KEY (idusuario) REFERENCES usuario(idusuario),
    CHECK (idproveedor IS NOT NULL OR idfabricante IS NOT NULL)
);

CREATE TABLE detalle_compra (
    iddetallecompra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcompra INT NOT NULL,
    idproducto INT NOT NULL,
    cantidad INT NOT NULL,
    costo_unitario DOUBLE PRECISION NOT NULL,
    subtotal DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (idcompra) REFERENCES compra(idcompra) ON DELETE CASCADE,
    FOREIGN KEY (idproducto) REFERENCES producto(idproducto)
);

-- ==========================================
-- 7. DATOS INICIALES (INSERTS & TESTING)
-- ==========================================

INSERT INTO usuario (idusuario, nombreusuario, contrasenausuario, permiso) VALUES 
(1, 'admin', 'admin', TRUE);