CREATE TABLE configuracion (
    clave VARCHAR(50) PRIMARY KEY,
    valor VARCHAR(255)
);

INSERT INTO configuracion (clave, valor) VALUES ('TIPO_CAMBIO_USD_MXN', '20.50');

ALTER TABLE producto ADD COLUMN monedaproducto VARCHAR(3) DEFAULT 'MXN';

ALTER TABLE venta ADD COLUMN moneda VARCHAR(3) DEFAULT 'MXN';
ALTER TABLE venta ADD COLUMN tipo_cambio DOUBLE PRECISION DEFAULT 1.0;

ALTER TABLE compra ADD COLUMN moneda VARCHAR(3) DEFAULT 'MXN';
ALTER TABLE compra ADD COLUMN tipo_cambio DOUBLE PRECISION DEFAULT 1.0;